export type SettingKind = "toggle" | "select" | "text" | "number" | "code";
export type SettingValue = boolean | number | string;

export type SettingOption = {
  key: string;
  label: string;
  section: string;
  description: string;
  type: SettingKind;
  options?: string[];
  placeholder?: string;
  defaultValue?: SettingValue;
  risk?: "high";
};

const row = (
  key: string,
  label: string,
  section: string,
  type: SettingKind,
  description: string,
  extra: Partial<SettingOption> = {},
): SettingOption => ({ key, label, section, type, description, ...extra });

export const settingOptions: SettingOption[] = [
  row("model", "Model", "model", "text", "Model used for new Codex turns.", {
    defaultValue: "gpt-5.5",
    placeholder: "gpt-5.5",
  }),
  row("review_model", "Review model", "model", "text", "Optional model override used by /review.", {
    placeholder: "Uses the current session model",
  }),
  row(
    "model_provider",
    "Model provider",
    "model",
    "text",
    "Provider id from model_providers. Defaults to openai.",
    { defaultValue: "openai", placeholder: "openai" },
  ),
  row(
    "openai_base_url",
    "OpenAI base URL",
    "model",
    "text",
    "Base URL override for the built-in OpenAI provider.",
    { placeholder: "https://api.openai.com/v1" },
  ),
  row(
    "model_context_window",
    "Context window",
    "model",
    "number",
    "Context window tokens available to the active model.",
    { placeholder: "Model default" },
  ),
  row(
    "model_auto_compact_token_limit",
    "Auto-compact token limit",
    "model",
    "number",
    "Token threshold that triggers automatic history compaction.",
    { placeholder: "Model default" },
  ),
  row(
    "model_auto_compact_token_limit_scope",
    "Auto-compact scope",
    "model",
    "select",
    "Choose whether the threshold counts the full context or only new growth.",
    { options: ["total", "body_after_prefix"], defaultValue: "total" },
  ),
  row(
    "model_catalog_json",
    "Model catalog path",
    "model",
    "text",
    "Optional path to a JSON model catalog loaded on startup.",
    { placeholder: "$CODEX_HOME/models.json" },
  ),
  row(
    "oss_provider",
    "Local provider",
    "model",
    "select",
    "Default local provider when running Codex with --oss.",
    { options: ["lmstudio", "ollama"], placeholder: "Ask on startup" },
  ),
  row(
    "model_reasoning_effort",
    "Reasoning effort",
    "model",
    "select",
    "Adjust reasoning effort for supported models.",
    { options: ["minimal", "low", "medium", "high", "xhigh"], defaultValue: "high" },
  ),
  row(
    "plan_mode_reasoning_effort",
    "Plan mode effort",
    "model",
    "select",
    "Plan-mode-specific reasoning override.",
    { options: ["none", "minimal", "low", "medium", "high", "xhigh"], defaultValue: "medium" },
  ),
  row(
    "model_reasoning_summary",
    "Reasoning summaries",
    "model",
    "select",
    "Select reasoning summary detail or disable summaries.",
    { options: ["auto", "concise", "detailed", "none"], defaultValue: "auto" },
  ),
  row(
    "model_verbosity",
    "Response verbosity",
    "model",
    "select",
    "Optional GPT-5 Responses API verbosity override.",
    { options: ["low", "medium", "high"], defaultValue: "medium" },
  ),
  row(
    "model_supports_reasoning_summaries",
    "Send reasoning metadata",
    "model",
    "toggle",
    "Force Codex to send or not send reasoning metadata.",
    { defaultValue: true },
  ),
  row(
    "service_tier",
    "Service tier",
    "model",
    "select",
    "Preferred service tier for new turns. Fast maps to request priority.",
    { options: ["default", "fast"], defaultValue: "default" },
  ),
  row(
    "personality",
    "Personality",
    "model",
    "select",
    "Default communication style for models that support personality.",
    { options: ["none", "friendly", "pragmatic"], defaultValue: "friendly" },
  ),
  row(
    "developer_instructions",
    "Developer instructions",
    "model",
    "code",
    "Additional developer instructions injected into each session.",
    { placeholder: "Optional instructions" },
  ),
  row(
    "instructions",
    "Legacy instructions",
    "model",
    "code",
    "Reserved for future use; prefer model_instructions_file or AGENTS.md.",
    { placeholder: "Optional instructions" },
  ),
  row(
    "compact_prompt",
    "Compaction prompt",
    "model",
    "code",
    "Inline override for the history compaction prompt.",
    { placeholder: "Optional prompt" },
  ),
  row(
    "model_instructions_file",
    "Instructions file",
    "model",
    "text",
    "Replacement for built-in instructions instead of AGENTS.md.",
    { placeholder: "~/AGENTS.md" },
  ),

  row(
    "approval_policy",
    "Approval policy",
    "safety",
    "select",
    "Controls when Codex pauses before executing commands.",
    { options: ["untrusted", "on-request", "never"], defaultValue: "on-request", risk: "high" },
  ),
  row(
    "approvals_reviewer",
    "Approval reviewer",
    "safety",
    "select",
    "Who reviews eligible approval prompts under interactive policies.",
    { options: ["user", "auto_review"], defaultValue: "user" },
  ),
  row(
    "approval_policy.granular.sandbox_approval",
    "Sandbox approvals",
    "safety",
    "toggle",
    "Allow sandbox escalation approval prompts to surface.",
    { defaultValue: true },
  ),
  row(
    "approval_policy.granular.rules",
    "Execpolicy prompts",
    "safety",
    "toggle",
    "Allow approvals triggered by execpolicy prompt rules.",
    { defaultValue: true },
  ),
  row(
    "approval_policy.granular.mcp_elicitations",
    "MCP elicitations",
    "safety",
    "toggle",
    "Allow MCP elicitation prompts to surface.",
    { defaultValue: true },
  ),
  row(
    "approval_policy.granular.request_permissions",
    "Permission requests",
    "safety",
    "toggle",
    "Allow prompts from the request_permissions tool to surface.",
    { defaultValue: true },
  ),
  row(
    "approval_policy.granular.skill_approval",
    "Skill approvals",
    "safety",
    "toggle",
    "Allow skill-script approval prompts to surface.",
    { defaultValue: true },
  ),
  row(
    "sandbox_mode",
    "Sandbox mode",
    "safety",
    "select",
    "Filesystem and network access policy during command execution.",
    {
      options: ["read-only", "workspace-write", "danger-full-access"],
      defaultValue: "workspace-write",
      risk: "high",
    },
  ),
  row(
    "sandbox_workspace_write.writable_roots",
    "Writable roots",
    "safety",
    "code",
    "Additional writable roots when workspace-write is active.",
    { placeholder: '["~/Code/shared"]' },
  ),
  row(
    "sandbox_workspace_write.network_access",
    "Workspace network access",
    "safety",
    "toggle",
    "Allow outbound network access inside workspace-write.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "sandbox_workspace_write.exclude_tmpdir_env_var",
    "Exclude TMPDIR",
    "safety",
    "toggle",
    "Exclude TMPDIR from writable roots in workspace-write mode.",
    { defaultValue: false },
  ),
  row(
    "sandbox_workspace_write.exclude_slash_tmp",
    "Exclude /tmp",
    "safety",
    "toggle",
    "Exclude /tmp from writable roots in workspace-write mode.",
    { defaultValue: false },
  ),
  row(
    "allow_login_shell",
    "Allow login shell",
    "safety",
    "toggle",
    "Allow shell-based tools to use login-shell semantics.",
    { defaultValue: true },
  ),
  row(
    "default_permissions",
    "Default permissions profile",
    "safety",
    "text",
    "Named permissions profile applied to sandboxed tool calls.",
    { placeholder: ":workspace" },
  ),
  row(
    "check_for_update_on_startup",
    "Check for updates",
    "safety",
    "toggle",
    "Check for Codex updates on startup.",
    { defaultValue: true },
  ),
  row(
    "feedback.enabled",
    "Feedback submission",
    "safety",
    "toggle",
    "Enable feedback submission via /feedback.",
    { defaultValue: true },
  ),
  row(
    "analytics.enabled",
    "Analytics",
    "safety",
    "toggle",
    "Enable or disable analytics for this machine or profile.",
    { defaultValue: true },
  ),

  row(
    "shell_environment_policy.inherit",
    "Environment inheritance",
    "shell",
    "select",
    "Baseline environment inheritance when spawning subprocesses.",
    { options: ["all", "core", "none"], defaultValue: "core" },
  ),
  row(
    "shell_environment_policy.ignore_default_excludes",
    "Keep secret-named variables",
    "shell",
    "toggle",
    "Keep variables containing KEY, SECRET, or TOKEN before filters run.",
    { defaultValue: true },
  ),
  row(
    "shell_environment_policy.filters",
    "Environment filters",
    "shell",
    "code",
    "Canonical environment-variable pattern filters.",
    { placeholder: '{ PATH = "include", NODE_ENV = "include" }' },
  ),
  row(
    "shell_environment_policy.exclude",
    "Excluded variables",
    "shell",
    "code",
    "Legacy environment-variable exclusion patterns.",
    { placeholder: '["AWS_SECRET_*"]' },
  ),
  row(
    "shell_environment_policy.include_only",
    "Allowed variables",
    "shell",
    "code",
    "Legacy allowlist of environment-variable patterns.",
    { placeholder: '["PATH", "HOME"]' },
  ),
  row(
    "shell_environment_policy.set",
    "Injected variables",
    "shell",
    "code",
    "Explicit environment values injected after exclusions.",
    { placeholder: '{ PROJECT_MODE = "dev" }' },
  ),
  row(
    "shell_environment_policy.experimental_use_profile",
    "Use shell profile",
    "shell",
    "toggle",
    "Use the user shell profile when spawning subprocesses.",
    { defaultValue: false },
  ),
  row(
    "project_root_markers",
    "Project root markers",
    "shell",
    "code",
    "Filenames used when searching parent directories for a project root.",
    { placeholder: '[".git", "package.json"]' },
  ),
  row(
    "project_doc_max_bytes",
    "AGENTS.md byte limit",
    "shell",
    "number",
    "Maximum bytes read from AGENTS.md for project instructions.",
    { defaultValue: 32768 },
  ),
  row(
    "project_doc_fallback_filenames",
    "Fallback instruction files",
    "shell",
    "code",
    "Additional filenames to try when AGENTS.md is missing.",
    { placeholder: '["INSTRUCTIONS.md"]' },
  ),
  row("log_dir", "Log directory", "shell", "text", "Directory where Codex writes log files.", {
    placeholder: "$CODEX_HOME/log",
  }),
  row(
    "sqlite_home",
    "SQLite state directory",
    "shell",
    "text",
    "Directory where Codex stores resumable runtime state.",
    { placeholder: "$CODEX_HOME/state" },
  ),
  row(
    "history.persistence",
    "History persistence",
    "shell",
    "select",
    "Control whether Codex saves session transcripts.",
    { options: ["save-all", "none"], defaultValue: "save-all" },
  ),
  row(
    "history.max_bytes",
    "History size limit",
    "shell",
    "number",
    "Cap the history file size by dropping oldest entries.",
    { placeholder: "Unlimited" },
  ),
  row(
    "tool_output_token_limit",
    "Tool output token limit",
    "shell",
    "number",
    "Token budget for storing individual tool outputs in history.",
    { defaultValue: 10000 },
  ),
  row(
    "background_terminal_max_timeout",
    "Background terminal timeout",
    "shell",
    "number",
    "Maximum poll window for empty background terminal polls.",
    { defaultValue: 300000 },
  ),
  row(
    "file_opener",
    "File opener",
    "shell",
    "select",
    "URI scheme used to open citations from Codex output.",
    {
      options: ["vscode", "vscode-insiders", "windsurf", "cursor", "none"],
      defaultValue: "vscode",
    },
  ),

  row(
    "features.apps",
    "Apps and connectors",
    "tools",
    "toggle",
    "Enable app and connector integrations.",
    { defaultValue: true },
  ),
  row(
    "apps._default.enabled",
    "Apps enabled by default",
    "tools",
    "toggle",
    "Default enabled state for all apps unless overridden.",
    { defaultValue: true },
  ),
  row(
    "apps._default.destructive_enabled",
    "Destructive app tools",
    "tools",
    "toggle",
    "Default allow or deny for destructive app tools.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "apps._default.open_world_enabled",
    "Open-world app tools",
    "tools",
    "toggle",
    "Default allow or deny for open-world app tools.",
    { defaultValue: false },
  ),
  row(
    "apps._default.approvals_reviewer",
    "App approval reviewer",
    "tools",
    "select",
    "Default reviewer for app tool approval prompts.",
    { options: ["user", "auto_review"], defaultValue: "user" },
  ),
  row(
    "apps._default.default_tools_approval_mode",
    "App tool approval mode",
    "tools",
    "select",
    "Default approval behavior for app tools.",
    { options: ["auto", "prompt", "writes", "approve"], defaultValue: "prompt" },
  ),
  row(
    "apps.<id>.enabled",
    "Specific app enabled",
    "tools",
    "toggle",
    "Enable or disable one app or connector by id.",
    { defaultValue: true },
  ),
  row(
    "apps.<id>.destructive_enabled",
    "Specific destructive tools",
    "tools",
    "toggle",
    "Allow destructive tools for one app.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "apps.<id>.open_world_enabled",
    "Specific open-world tools",
    "tools",
    "toggle",
    "Allow open-world tools for one app.",
    { defaultValue: false },
  ),
  row(
    "apps.<id>.default_tools_enabled",
    "Specific app tools",
    "tools",
    "toggle",
    "Default enabled state for tools in one app.",
    { defaultValue: true },
  ),
  row(
    "apps.<id>.approvals_reviewer",
    "Specific app reviewer",
    "tools",
    "select",
    "Reviewer for one app's tool approval prompts.",
    { options: ["user", "auto_review"] },
  ),
  row(
    "apps.<id>.default_tools_approval_mode",
    "Specific app approval mode",
    "tools",
    "select",
    "Default approval behavior for tools in one app.",
    { options: ["auto", "prompt", "writes", "approve"] },
  ),
  row(
    "apps.<id>.tools.<tool>.enabled",
    "Per-tool enabled override",
    "tools",
    "toggle",
    "Enable or disable one tool in an app.",
    { defaultValue: true },
  ),
  row(
    "apps.<id>.tools.<tool>.approval_mode",
    "Per-tool approval mode",
    "tools",
    "select",
    "Approval behavior override for one app tool.",
    { options: ["auto", "prompt", "writes", "approve"] },
  ),
  row(
    "mcp_servers.<id>.command",
    "MCP command",
    "tools",
    "text",
    "Launcher command for an MCP stdio server.",
    { placeholder: "npx" },
  ),
  row(
    "mcp_servers.<id>.args",
    "MCP arguments",
    "tools",
    "code",
    "Arguments passed to an MCP stdio server command.",
    { placeholder: '["-y", "@modelcontextprotocol/server-github"]' },
  ),
  row(
    "mcp_servers.<id>.env",
    "MCP environment",
    "tools",
    "code",
    "Environment variables forwarded to an MCP stdio server.",
    { placeholder: '{ GITHUB_TOKEN = "..." }' },
  ),
  row(
    "mcp_servers.<id>.env_vars",
    "MCP allowed environment",
    "tools",
    "code",
    "Environment variables to whitelist for an MCP stdio server.",
    { placeholder: '["HOME"]' },
  ),
  row(
    "mcp_servers.<id>.cwd",
    "MCP working directory",
    "tools",
    "text",
    "Working directory for the MCP server process.",
    { placeholder: "~/Code/project" },
  ),
  row(
    "mcp_servers.<id>.url",
    "MCP HTTP URL",
    "tools",
    "text",
    "Endpoint for an MCP streamable HTTP server.",
    { placeholder: "https://mcp.example.com" },
  ),
  row(
    "mcp_servers.<id>.auth",
    "MCP auth fallback",
    "tools",
    "select",
    "Authentication fallback for an MCP HTTP server.",
    { options: ["oauth", "chatgpt"], defaultValue: "oauth" },
  ),
  row(
    "mcp_servers.<id>.bearer_token_env_var",
    "MCP bearer token variable",
    "tools",
    "text",
    "Environment variable sourcing an MCP bearer token.",
    { placeholder: "MCP_TOKEN" },
  ),
  row(
    "mcp_servers.<id>.http_headers",
    "MCP HTTP headers",
    "tools",
    "code",
    "Static HTTP headers included with each MCP request.",
    { placeholder: '{ "X-Team" = "platform" }' },
  ),
  row(
    "mcp_servers.<id>.env_http_headers",
    "MCP environment headers",
    "tools",
    "code",
    "HTTP headers populated from environment variables.",
    { placeholder: '{ Authorization = "MCP_AUTH" }' },
  ),
  row(
    "mcp_servers.<id>.enabled",
    "MCP server enabled",
    "tools",
    "toggle",
    "Disable an MCP server without removing its configuration.",
    { defaultValue: true },
  ),
  row(
    "mcp_servers.<id>.required",
    "MCP server required",
    "tools",
    "toggle",
    "Fail startup if this enabled MCP server cannot initialize.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "mcp_servers.<id>.startup_timeout_sec",
    "MCP startup timeout",
    "tools",
    "number",
    "Override the default 10 second startup timeout.",
    { defaultValue: 10 },
  ),
  row(
    "mcp_servers.<id>.tool_timeout_sec",
    "MCP tool timeout",
    "tools",
    "number",
    "Override the default 60 second per-tool timeout.",
    { defaultValue: 60 },
  ),
  row(
    "mcp_servers.<id>.enabled_tools",
    "MCP enabled tools",
    "tools",
    "code",
    "Allow list of tool names exposed by the server.",
    { placeholder: '["search", "fetch"]' },
  ),
  row(
    "mcp_servers.<id>.disabled_tools",
    "MCP disabled tools",
    "tools",
    "code",
    "Deny list applied after enabled_tools.",
    { placeholder: '["delete"]' },
  ),
  row(
    "mcp_servers.<id>.default_tools_approval_mode",
    "MCP approval mode",
    "tools",
    "select",
    "Default approval behavior for MCP tools.",
    { options: ["auto", "prompt", "writes", "approve"], defaultValue: "prompt" },
  ),
  row(
    "mcp_servers.<id>.scopes",
    "MCP OAuth scopes",
    "tools",
    "code",
    "OAuth scopes requested when authenticating to an MCP server.",
    { placeholder: '["repo:read"]' },
  ),
  row(
    "mcp_servers.<id>.oauth_resource",
    "MCP OAuth resource",
    "tools",
    "text",
    "Optional RFC 8707 OAuth resource parameter.",
    { placeholder: "https://mcp.example.com" },
  ),
  row(
    "mcp_servers.<id>.experimental_environment",
    "MCP environment",
    "tools",
    "select",
    "Experimental placement for an MCP server.",
    { options: ["local", "remote"], defaultValue: "local" },
  ),
  row(
    "tools.web_search",
    "Web search tool",
    "tools",
    "code",
    "Optional web search tool configuration.",
    { placeholder: 'true or { context_size = "medium" }' },
  ),
  row(
    "tools.view_image",
    "View image tool",
    "tools",
    "toggle",
    "Enable the local-image attachment tool.",
    { defaultValue: true },
  ),
  row("web_search", "Web search mode", "tools", "select", "Select the default search mode.", {
    options: ["disabled", "cached", "indexed", "live"],
    defaultValue: "cached",
  }),
  row(
    "notify",
    "Notification command",
    "tools",
    "code",
    "Command invoked for notifications with a JSON payload.",
    { placeholder: '["notify-send", "Codex"]' },
  ),
  row(
    "tool_suggest.discoverables",
    "Suggested discoverables",
    "tools",
    "code",
    "Connectors or plugins eligible for tool suggestions.",
    { placeholder: '[{ type = "connector", id = "github" }]' },
  ),
  row(
    "tool_suggest.disabled_tools",
    "Disabled suggestions",
    "tools",
    "code",
    "Connectors or plugins excluded from tool suggestions.",
    { placeholder: '[{ type = "plugin", id = "example" }]' },
  ),

  row(
    "agents.enabled",
    "Multi-agent tools",
    "agents",
    "toggle",
    "Enable or disable multi-agent tools.",
    { defaultValue: true },
  ),
  row(
    "agents.max_concurrent_threads_per_session",
    "Concurrent agent threads",
    "agents",
    "number",
    "Maximum spawned-agent threads open concurrently per session.",
    { defaultValue: 4 },
  ),
  row(
    "agents.max_threads",
    "Legacy thread limit",
    "agents",
    "number",
    "Legacy alias for max_concurrent_threads_per_session.",
    { placeholder: "Use the current key instead" },
  ),
  row(
    "agents.default_subagent_model",
    "Subagent model",
    "agents",
    "text",
    "Default model for spawned agents.",
    { placeholder: "Inherit current model" },
  ),
  row(
    "agents.default_subagent_reasoning_effort",
    "Subagent reasoning effort",
    "agents",
    "select",
    "Default reasoning effort for spawned agents.",
    {
      options: ["minimal", "low", "medium", "high", "xhigh"],
      placeholder: "Inherit current effort",
    },
  ),
  row(
    "agents.interrupt_message",
    "Agent interrupt messages",
    "agents",
    "toggle",
    "Record a model-visible message when an agent turn is interrupted.",
    { defaultValue: true },
  ),
  row(
    "agents.<name>.description",
    "Custom agent description",
    "agents",
    "code",
    "Role guidance shown when choosing and spawning an agent type.",
    { placeholder: "A concise role description" },
  ),
  row(
    "agents.<name>.config_file",
    "Custom agent config",
    "agents",
    "text",
    "Path to a TOML config layer for that role.",
    { placeholder: "$CODEX_HOME/reviewer.config.toml" },
  ),

  row(
    "features.hooks",
    "Lifecycle hooks",
    "features",
    "toggle",
    "Enable lifecycle hooks from hooks.json or inline config.",
    { defaultValue: true },
  ),
  row(
    "features.code_mode.enabled",
    "Code mode",
    "features",
    "toggle",
    "Enable the under-development code mode feature.",
    { defaultValue: false },
  ),
  row(
    "features.code_mode.excluded_tool_namespaces",
    "Code mode excluded namespaces",
    "features",
    "code",
    "Tool namespaces excluded from code mode guidance.",
    { placeholder: '["browser"]' },
  ),
  row(
    "features.code_mode.direct_only_tool_namespaces",
    "Code mode direct-only namespaces",
    "features",
    "code",
    "Tool namespaces available only through direct calls.",
    { placeholder: '["terminal"]' },
  ),
  row(
    "features.rollout_budget.enabled",
    "Rollout budget",
    "features",
    "toggle",
    "Enable rollout budget tracking.",
    { defaultValue: false },
  ),
  row(
    "features.rollout_budget.limit_tokens",
    "Rollout budget limit",
    "features",
    "number",
    "Positive token limit required when rollout budget is enabled.",
    { placeholder: "100000" },
  ),
  row(
    "features.rollout_budget.reminder_interval_tokens",
    "Rollout reminder interval",
    "features",
    "number",
    "Token interval between rollout budget reminders.",
    { placeholder: "10% of limit" },
  ),
  row(
    "features.rollout_budget.sampling_token_weight",
    "Sampled token weight",
    "features",
    "number",
    "Non-negative multiplier for sampled tokens.",
    { defaultValue: 1 },
  ),
  row(
    "features.rollout_budget.prefill_token_weight",
    "Prefill token weight",
    "features",
    "number",
    "Non-negative multiplier for prefill tokens.",
    { defaultValue: 1 },
  ),
  row("features.memories", "Memories", "features", "toggle", "Enable memories.", {
    defaultValue: false,
  }),
  row(
    "memories.generate_memories",
    "Generate memories",
    "features",
    "toggle",
    "Use newly created threads as memory-generation inputs.",
    { defaultValue: true },
  ),
  row(
    "memories.use_memories",
    "Use memories",
    "features",
    "toggle",
    "Inject existing memories into future sessions.",
    { defaultValue: true },
  ),
  row(
    "memories.disable_on_external_context",
    "Skip external-context memories",
    "features",
    "toggle",
    "Keep threads using MCP, web search, or tool search out of memory generation.",
    { defaultValue: false },
  ),
  row(
    "memories.max_raw_memories_for_consolidation",
    "Raw memories limit",
    "features",
    "number",
    "Maximum recent raw memories retained for consolidation.",
    { defaultValue: 256 },
  ),
  row(
    "memories.max_unused_days",
    "Unused memory age",
    "features",
    "number",
    "Days since last use before a memory becomes ineligible.",
    { defaultValue: 30 },
  ),
  row(
    "memories.max_rollout_age_days",
    "Rollout age",
    "features",
    "number",
    "Maximum age of threads considered for memory generation.",
    { defaultValue: 30 },
  ),
  row(
    "memories.max_rollouts_per_startup",
    "Rollouts per startup",
    "features",
    "number",
    "Maximum rollout candidates processed at startup.",
    { defaultValue: 16 },
  ),
  row(
    "memories.min_rollout_idle_hours",
    "Minimum idle hours",
    "features",
    "number",
    "Minimum idle time before a thread is considered.",
    { defaultValue: 6 },
  ),
  row(
    "memories.min_rate_limit_remaining_percent",
    "Minimum rate-limit remaining",
    "features",
    "number",
    "Minimum remaining percentage before memory generation starts.",
    { defaultValue: 25 },
  ),
  row(
    "memories.extract_model",
    "Memory extraction model",
    "features",
    "text",
    "Optional model override for per-thread memory extraction.",
    { placeholder: "Current model" },
  ),
  row(
    "memories.consolidation_model",
    "Memory consolidation model",
    "features",
    "text",
    "Optional model override for global memory consolidation.",
    { placeholder: "Current model" },
  ),
  row(
    "features.unified_exec",
    "Unified exec",
    "features",
    "toggle",
    "Use the unified PTY-backed exec tool.",
    { defaultValue: true },
  ),
  row(
    "features.shell_snapshot",
    "Shell snapshot",
    "features",
    "toggle",
    "Snapshot the shell environment to speed up repeated commands.",
    { defaultValue: true },
  ),
  row(
    "features.multi_agent",
    "Multi-agent collaboration",
    "features",
    "toggle",
    "Enable spawn, send, resume, wait, and close agent tools.",
    { defaultValue: true },
  ),
  row(
    "features.goals",
    "Persisted goals",
    "features",
    "toggle",
    "Enable persisted goals and automatic continuation.",
    { defaultValue: true },
  ),
  row(
    "features.remote_plugin",
    "Remote plugin catalog",
    "features",
    "toggle",
    "Enable the remote plugin catalog.",
    { defaultValue: true },
  ),
  row(
    "features.personality",
    "Personality controls",
    "features",
    "toggle",
    "Enable personality selection controls.",
    { defaultValue: true },
  ),
  row(
    "features.shell_tool",
    "Shell tool",
    "features",
    "toggle",
    "Enable the default shell tool for running commands.",
    { defaultValue: true },
  ),
  row(
    "features.enable_request_compression",
    "Request compression",
    "features",
    "toggle",
    "Compress streaming request bodies with zstd when supported.",
    { defaultValue: true },
  ),
  row(
    "features.skill_mcp_dependency_install",
    "Skill dependency install",
    "features",
    "toggle",
    "Allow installing missing MCP dependencies for skills.",
    { defaultValue: true },
  ),
  row(
    "features.fast_mode",
    "Fast mode",
    "features",
    "toggle",
    "Enable model-catalog service tier selection in the TUI.",
    { defaultValue: true },
  ),
  row(
    "features.prevent_idle_sleep",
    "Prevent idle sleep",
    "features",
    "toggle",
    "Prevent the machine from sleeping while a turn runs.",
    { defaultValue: false },
  ),
  row(
    "suppress_unstable_features_warning",
    "Hide unstable feature warnings",
    "features",
    "toggle",
    "Suppress warnings when under-development feature flags are enabled.",
    { defaultValue: false },
  ),
  row(
    "features.network_proxy.enabled",
    "Sandboxed networking",
    "features",
    "toggle",
    "Enable the sandboxed network proxy.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "features.network_proxy.domains",
    "Network domain policy",
    "features",
    "code",
    "Allow or deny domains for sandboxed networking.",
    { placeholder: '{ "api.example.com" = "allow" }' },
  ),
  row(
    "features.network_proxy.unix_sockets",
    "Network Unix sockets",
    "features",
    "code",
    "Allow or deny Unix sockets for sandboxed networking.",
    { placeholder: '{ "/var/run/docker.sock" = "deny" }' },
  ),
  row(
    "features.network_proxy.allow_local_binding",
    "Allow local binding",
    "features",
    "toggle",
    "Allow broader local and private-network access.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "features.network_proxy.enable_socks5",
    "Enable SOCKS5",
    "features",
    "toggle",
    "Expose SOCKS5 support.",
    { defaultValue: true },
  ),
  row(
    "features.network_proxy.enable_socks5_udp",
    "Enable SOCKS5 UDP",
    "features",
    "toggle",
    "Allow UDP over SOCKS5.",
    { defaultValue: true },
  ),
  row(
    "features.network_proxy.allow_upstream_proxy",
    "Allow upstream proxy",
    "features",
    "toggle",
    "Allow chaining through an upstream proxy from the environment.",
    { defaultValue: true },
  ),
  row(
    "features.network_proxy.dangerously_allow_non_loopback_proxy",
    "Allow non-loopback proxy",
    "features",
    "toggle",
    "Permit proxy listener addresses beyond loopback.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "features.network_proxy.proxy_url",
    "HTTP proxy URL",
    "features",
    "text",
    "HTTP listener URL for sandboxed networking.",
    { defaultValue: "http://127.0.0.1:3128" },
  ),
  row(
    "features.network_proxy.socks_url",
    "SOCKS5 proxy URL",
    "features",
    "text",
    "SOCKS5 listener URL.",
    { defaultValue: "http://127.0.0.1:8081" },
  ),

  row(
    "model_providers.<id>.name",
    "Provider name",
    "providers",
    "text",
    "Display name for a custom model provider.",
    { placeholder: "My provider" },
  ),
  row(
    "model_providers.<id>.base_url",
    "Provider base URL",
    "providers",
    "text",
    "API base URL for a custom provider.",
    { placeholder: "https://api.example.com/v1" },
  ),
  row(
    "model_providers.<id>.env_key",
    "Provider API key variable",
    "providers",
    "text",
    "Environment variable supplying the provider API key.",
    { placeholder: "MY_PROVIDER_API_KEY" },
  ),
  row(
    "model_providers.<id>.env_key_instructions",
    "API key instructions",
    "providers",
    "code",
    "Optional setup guidance for the provider API key.",
    { placeholder: "Set MY_PROVIDER_API_KEY before starting Codex." },
  ),
  row(
    "model_providers.<id>.experimental_bearer_token",
    "Bearer token",
    "providers",
    "text",
    "Direct bearer token for a custom provider. Prefer env_key.",
    { placeholder: "Discouraged" },
  ),
  row(
    "model_providers.<id>.requires_openai_auth",
    "Use OpenAI auth",
    "providers",
    "toggle",
    "Whether the provider uses OpenAI authentication.",
    { defaultValue: false },
  ),
  row(
    "model_providers.<id>.wire_api",
    "Wire API",
    "providers",
    "select",
    "Protocol used by the provider.",
    { options: ["responses"], defaultValue: "responses" },
  ),
  row(
    "model_providers.<id>.query_params",
    "Provider query params",
    "providers",
    "code",
    "Extra query parameters appended to provider requests.",
    { placeholder: '{ api_version = "2025-01-01" }' },
  ),
  row(
    "model_providers.<id>.http_headers",
    "Provider HTTP headers",
    "providers",
    "code",
    "Static headers added to provider requests.",
    { placeholder: '{ "X-Environment" = "dev" }' },
  ),
  row(
    "model_providers.<id>.env_http_headers",
    "Provider environment headers",
    "providers",
    "code",
    "Headers populated from environment variables.",
    { placeholder: '{ "X-Org" = "ORG_ID" }' },
  ),
  row(
    "model_providers.<id>.request_max_retries",
    "Request retries",
    "providers",
    "number",
    "Retry count for provider HTTP requests.",
    { defaultValue: 4 },
  ),
  row(
    "model_providers.<id>.stream_max_retries",
    "Stream retries",
    "providers",
    "number",
    "Retry count for streaming interruptions.",
    { defaultValue: 5 },
  ),
  row(
    "model_providers.<id>.stream_idle_timeout_ms",
    "Stream idle timeout",
    "providers",
    "number",
    "Idle timeout for SSE streams in milliseconds.",
    { defaultValue: 300000 },
  ),
  row(
    "model_providers.<id>.supports_websockets",
    "Supports WebSockets",
    "providers",
    "toggle",
    "Whether the provider supports Responses API WebSockets.",
    { defaultValue: false },
  ),
  row(
    "model_providers.<id>.supports_standalone_web_search",
    "Supports standalone search",
    "providers",
    "toggle",
    "Advertise a compatible standalone web search endpoint.",
    { defaultValue: false },
  ),
  row(
    "model_providers.<id>.auth.command",
    "Token command",
    "providers",
    "text",
    "Command that prints a custom provider bearer token.",
    { placeholder: "op read secret/..." },
  ),
  row(
    "model_providers.<id>.auth.args",
    "Token command args",
    "providers",
    "code",
    "Arguments passed to the token command.",
    { placeholder: '["--format", "raw"]' },
  ),
  row(
    "model_providers.<id>.auth.timeout_ms",
    "Token timeout",
    "providers",
    "number",
    "Maximum token command runtime in milliseconds.",
    { defaultValue: 5000 },
  ),
  row(
    "model_providers.<id>.auth.refresh_interval_ms",
    "Token refresh interval",
    "providers",
    "number",
    "How often Codex proactively refreshes the token.",
    { defaultValue: 300000 },
  ),
  row(
    "model_providers.amazon-bedrock.aws.profile",
    "Bedrock AWS profile",
    "providers",
    "text",
    "AWS profile used by the built-in Amazon Bedrock provider.",
    { placeholder: "default" },
  ),
  row(
    "model_providers.amazon-bedrock.aws.region",
    "Bedrock AWS region",
    "providers",
    "text",
    "AWS region used by the built-in Amazon Bedrock provider.",
    { placeholder: "us-east-1" },
  ),

  row(
    "tui.notifications",
    "Notifications",
    "tui",
    "toggle",
    "Enable TUI notifications, optionally restricted to events.",
    { defaultValue: true },
  ),
  row(
    "tui.notification_method",
    "Notification method",
    "tui",
    "select",
    "Notification method for terminal notifications.",
    { options: ["auto", "osc9", "bel"], defaultValue: "auto" },
  ),
  row(
    "tui.notification_condition",
    "Notification condition",
    "tui",
    "select",
    "Fire notifications only when unfocused or always.",
    { options: ["unfocused", "always"], defaultValue: "unfocused" },
  ),
  row(
    "tui.animations",
    "Animations",
    "tui",
    "toggle",
    "Enable terminal animations like the welcome shimmer and spinner.",
    { defaultValue: true },
  ),
  row(
    "tui.alternate_screen",
    "Alternate screen",
    "tui",
    "select",
    "Control alternate screen usage for the TUI.",
    { options: ["auto", "always", "never"], defaultValue: "auto" },
  ),
  row(
    "tui.resume_cwd",
    "Resume directory",
    "tui",
    "select",
    "Working directory when resuming or forking a session.",
    { options: ["current", "session"], defaultValue: "current" },
  ),
  row(
    "tui.vim_mode_default",
    "Vim mode by default",
    "tui",
    "toggle",
    "Start the composer in Vim normal mode.",
    { defaultValue: false },
  ),
  row(
    "tui.raw_output_mode",
    "Raw output mode",
    "tui",
    "toggle",
    "Start the TUI in copy-friendly raw scrollback mode.",
    { defaultValue: false },
  ),
  row(
    "tui.show_tooltips",
    "Show tooltips",
    "tui",
    "toggle",
    "Show onboarding tooltips on the TUI welcome screen.",
    { defaultValue: true },
  ),
  row(
    "tui.status_line",
    "Status line items",
    "tui",
    "code",
    "Ordered list of footer status-line item identifiers.",
    { placeholder: '["model", "context", "git"]' },
  ),
  row(
    "tui.terminal_title",
    "Terminal title items",
    "tui",
    "code",
    "Ordered list of terminal window or tab title identifiers.",
    { placeholder: '["spinner", "project"]' },
  ),
  row("tui.theme", "TUI theme", "tui", "text", "Syntax-highlighting theme override.", {
    placeholder: "catppuccin-mocha",
  }),
  row(
    "tui.keymap.<context>.<action>",
    "Keymap binding",
    "tui",
    "code",
    "Keyboard shortcut binding for a TUI action.",
    { placeholder: '"ctrl-shift-p"' },
  ),
  row(
    "hide_agent_reasoning",
    "Hide agent reasoning",
    "tui",
    "toggle",
    "Suppress reasoning events in the TUI and codex exec output.",
    { defaultValue: false },
  ),
  row(
    "show_raw_agent_reasoning",
    "Show raw agent reasoning",
    "tui",
    "toggle",
    "Surface raw reasoning content when the model emits it.",
    { defaultValue: false },
  ),
  row(
    "disable_paste_burst",
    "Disable paste burst",
    "tui",
    "toggle",
    "Disable burst-paste detection in the TUI.",
    { defaultValue: false },
  ),

  row(
    "otel.environment",
    "OTEL environment",
    "telemetry",
    "text",
    "Environment tag applied to emitted OpenTelemetry events.",
    { defaultValue: "dev" },
  ),
  row(
    "otel.exporter",
    "OTEL logs exporter",
    "telemetry",
    "select",
    "Select the OpenTelemetry logs exporter.",
    { options: ["none", "otlp-http", "otlp-grpc"], defaultValue: "none" },
  ),
  row(
    "otel.trace_exporter",
    "OTEL traces exporter",
    "telemetry",
    "select",
    "Select the OpenTelemetry trace exporter.",
    { options: ["none", "otlp-http", "otlp-grpc"], defaultValue: "none" },
  ),
  row(
    "otel.metrics_exporter",
    "OTEL metrics exporter",
    "telemetry",
    "select",
    "Select the OpenTelemetry metrics exporter.",
    { options: ["none", "statsig", "otlp-http", "otlp-grpc"], defaultValue: "statsig" },
  ),
  row(
    "otel.log_user_prompt",
    "Export raw prompts",
    "telemetry",
    "toggle",
    "Opt in to exporting raw user prompts with OTEL logs.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "otel.exporter.<id>.endpoint",
    "OTEL exporter endpoint",
    "telemetry",
    "text",
    "Exporter endpoint for OTEL logs.",
    { placeholder: "https://otel.example.com" },
  ),
  row(
    "otel.exporter.<id>.protocol",
    "OTEL exporter protocol",
    "telemetry",
    "select",
    "Protocol used by the OTLP/HTTP exporter.",
    { options: ["binary", "json"], defaultValue: "binary" },
  ),
  row(
    "otel.exporter.<id>.headers",
    "OTEL exporter headers",
    "telemetry",
    "code",
    "Static headers included with exporter requests.",
    { placeholder: '{ Authorization = "Bearer ..." }' },
  ),
  row(
    "chatgpt_base_url",
    "ChatGPT base URL",
    "telemetry",
    "text",
    "Base URL used during the ChatGPT login flow.",
    { placeholder: "https://chatgpt.com" },
  ),
  row(
    "cli_auth_credentials_store",
    "CLI credentials store",
    "telemetry",
    "select",
    "Where the CLI stores cached credentials.",
    { options: ["file", "keyring", "auto"], defaultValue: "auto" },
  ),
  row(
    "mcp_oauth_credentials_store",
    "MCP OAuth store",
    "telemetry",
    "select",
    "Preferred store for MCP OAuth credentials.",
    { options: ["auto", "file", "keyring"], defaultValue: "auto" },
  ),
  row(
    "mcp_oauth_callback_port",
    "MCP OAuth callback port",
    "telemetry",
    "number",
    "Optional fixed port for the local MCP OAuth callback server.",
    { placeholder: "Ephemeral" },
  ),
  row(
    "mcp_oauth_callback_url",
    "MCP OAuth callback URL",
    "telemetry",
    "text",
    "Optional base callback URL override for MCP OAuth login.",
    { placeholder: "https://devbox.example.com" },
  ),

  row(
    "permissions.<name>.description",
    "Permission profile description",
    "advanced",
    "text",
    "Human-readable description for a named permission profile.",
    { placeholder: "Safe workspace profile" },
  ),
  row(
    "permissions.<name>.extends",
    "Permission profile parent",
    "advanced",
    "text",
    "Optional parent profile applied before a named profile.",
    { placeholder: ":workspace" },
  ),
  row(
    "permissions.<name>.workspace_roots",
    "Permission workspace roots",
    "advanced",
    "code",
    "Profile-defined workspace roots for filesystem rules.",
    { placeholder: '{ "~/Code" = true }' },
  ),
  row(
    "permissions.<name>.filesystem",
    "Permission filesystem",
    "advanced",
    "code",
    "Named filesystem permissions for paths and special tokens.",
    { placeholder: '{ ":workspace_roots" = "write" }' },
  ),
  row(
    "permissions.<name>.filesystem.glob_scan_max_depth",
    "Filesystem glob depth",
    "advanced",
    "number",
    "Maximum depth for expanding deny-read glob patterns.",
    { defaultValue: 3 },
  ),
  row(
    "permissions.<name>.network.enabled",
    "Profile network access",
    "advanced",
    "toggle",
    "Enable network access for a named permissions profile.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "permissions.<name>.network.proxy_url",
    "Profile proxy URL",
    "advanced",
    "text",
    "HTTP listener URL used by a permissions profile.",
    { placeholder: "http://127.0.0.1:3128" },
  ),
  row(
    "permissions.<name>.network.mode",
    "Profile network mode",
    "advanced",
    "select",
    "Network proxy mode used for subprocess traffic.",
    { options: ["limited", "full"], defaultValue: "limited" },
  ),
  row(
    "permissions.<name>.network.domains",
    "Profile domain rules",
    "advanced",
    "code",
    "Domain rules for sandboxed networking.",
    { placeholder: '{ "github.com" = "allow" }' },
  ),
  row(
    "projects.<path>.trust_level",
    "Project trust level",
    "advanced",
    "select",
    "Mark a project or worktree as trusted or untrusted.",
    { options: ["trusted", "untrusted"], defaultValue: "trusted" },
  ),
  row(
    "windows.sandbox",
    "Windows sandbox",
    "advanced",
    "select",
    "Native sandbox mode when running Codex on Windows.",
    { options: ["unelevated", "elevated"], defaultValue: "unelevated" },
  ),
  row(
    "windows.sandbox_private_desktop",
    "Windows private desktop",
    "advanced",
    "toggle",
    "Run the final sandboxed child process on a private desktop.",
    { defaultValue: true },
  ),
  row(
    "computer_use.windows.always_allowed_app_ids",
    "Allowed Windows app ids",
    "advanced",
    "code",
    "Windows apps Computer Use can open without prompting.",
    { placeholder: '["com.microsoft.Edge"]' },
  ),
  row(
    "desktop.custom_file_handlers.<id>.label",
    "Custom handler label",
    "advanced",
    "text",
    "Display name for a desktop Open in target.",
    { placeholder: "Cursor" },
  ),
  row(
    "desktop.custom_file_handlers.<id>.command",
    "Custom handler command",
    "advanced",
    "text",
    "Executable path or command name for a desktop handler.",
    { placeholder: "cursor" },
  ),
  row(
    "desktop.custom_file_handlers.<id>.args",
    "Custom handler arguments",
    "advanced",
    "code",
    "Arguments inserted between the command and file input.",
    { placeholder: '["--reuse-window"]' },
  ),
  row(
    "desktop.custom_file_handlers.<id>.input",
    "Custom handler input",
    "advanced",
    "select",
    "How the app sends file input to a custom handler.",
    { options: ["path", "json_argument", "json_stdin"], defaultValue: "path" },
  ),
  row(
    "desktop.custom_file_handlers.<id>.supports_ssh",
    "Custom handler supports SSH",
    "advanced",
    "toggle",
    "Offer the handler for files in SSH workspaces.",
    { defaultValue: false },
  ),
  row(
    "notice.hide_full_access_warning",
    "Hide full-access warning",
    "advanced",
    "toggle",
    "Track acknowledgement of the full access warning.",
    { defaultValue: false },
  ),
  row(
    "notice.hide_rate_limit_model_nudge",
    "Hide rate-limit nudge",
    "advanced",
    "toggle",
    "Track opt-out of the rate-limit model switch reminder.",
    { defaultValue: false },
  ),
  row(
    "notice.model_migrations",
    "Acknowledged migrations",
    "advanced",
    "code",
    "Track acknowledged model migrations as old-to-new mappings.",
    { placeholder: '{ "old-model" = "new-model" }' },
  ),
  row(
    "forced_login_method",
    "Forced login method",
    "advanced",
    "select",
    "Restrict Codex to a specific authentication method.",
    { options: ["chatgpt", "api"], placeholder: "Allow either" },
  ),
  row(
    "forced_chatgpt_workspace_id",
    "Forced workspace id",
    "advanced",
    "text",
    "Limit ChatGPT logins to a specific workspace UUID.",
    { placeholder: "00000000-0000-0000-0000-000000000000" },
  ),
  row(
    "agents",
    "Agents table",
    "agents",
    "code",
    "Multi-agent settings and custom role declarations.",
    { placeholder: "[agents]" },
  ),
  row(
    "auto_review.policy",
    "Automatic review policy",
    "safety",
    "code",
    "Local Markdown policy instructions for automatic review.",
    { placeholder: "Optional review policy" },
  ),
  row(
    "desktop.custom_file_handlers.<id>",
    "Custom file handler",
    "advanced",
    "code",
    "Additional Open in target for the ChatGPT desktop app.",
    { placeholder: "[desktop.custom_file_handlers.cursor]" },
  ),
  row(
    "desktop.custom_file_handlers.<id>.icon",
    "Custom handler icon",
    "advanced",
    "text",
    "Asset path, data URL, file URI, or local path for a handler icon.",
    { placeholder: "/path/to/icon.png" },
  ),
  row(
    "experimental_compact_prompt_file",
    "Experimental prompt file",
    "model",
    "text",
    "Load a compaction prompt override from a file.",
    { placeholder: "~/compact-prompt.md" },
  ),
  row(
    "experimental_use_unified_exec_tool",
    "Legacy unified exec",
    "features",
    "toggle",
    "Legacy name for enabling unified exec; prefer features.unified_exec.",
    { defaultValue: false },
  ),
  row(
    "features.network_proxy",
    "Network proxy config",
    "features",
    "code",
    "Enable sandboxed networking or set its network policy options.",
    { placeholder: "true or { enabled = true }" },
  ),
  row(
    "features.network_proxy.dangerously_allow_all_unix_sockets",
    "Allow all Unix sockets",
    "features",
    "toggle",
    "Permit arbitrary Unix socket destinations instead of the allowlist.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "features.web_search",
    "Legacy web search",
    "features",
    "toggle",
    "Deprecated legacy web search toggle.",
    { defaultValue: false },
  ),
  row(
    "features.web_search_cached",
    "Legacy cached search",
    "features",
    "toggle",
    "Deprecated legacy toggle that maps to cached web search.",
    { defaultValue: false },
  ),
  row(
    "features.web_search_request",
    "Legacy live search",
    "features",
    "toggle",
    "Deprecated legacy toggle that maps to live web search.",
    { defaultValue: false },
  ),
  row(
    "hooks",
    "Hooks table",
    "tools",
    "code",
    "Lifecycle hooks configured inline in config.toml.",
    { placeholder: "[hooks]" },
  ),
  row(
    "hooks.<Event>",
    "Hook event matchers",
    "tools",
    "code",
    "Matcher groups for events such as PreToolUse, PostToolUse, or SessionEnd.",
    { placeholder: "[[hooks.PreToolUse]]" },
  ),
  row(
    "hooks.<Event>[].hooks",
    "Hook handlers",
    "tools",
    "code",
    "Command hook handlers for a matcher group.",
    { placeholder: "[[hooks.PreToolUse.hooks]]" },
  ),
  row(
    "hooks.<Event>[].hooks[].additionalContextLimit",
    "Hook context limit",
    "tools",
    "number",
    "Token threshold for shortening oversized additionalContext output.",
    { defaultValue: 2500 },
  ),
  row(
    "hooks.<Event>[].hooks[].commandWindows",
    "Windows hook command",
    "tools",
    "text",
    "Windows-only command override for command hooks.",
    { placeholder: "powershell.exe" },
  ),
  row(
    "mcp_servers.<id>.startup_timeout_ms",
    "MCP startup timeout alias",
    "tools",
    "number",
    "Alias for startup_timeout_sec in milliseconds.",
    { defaultValue: 10000 },
  ),
  row(
    "mcp_servers.<id>.tools.<tool>.approval_mode",
    "MCP per-tool approval",
    "tools",
    "select",
    "Approval behavior override for one MCP tool.",
    { options: ["auto", "prompt", "writes", "approve"] },
  ),
  row(
    "model_providers.<id>",
    "Custom provider",
    "providers",
    "code",
    "Custom provider definition; built-in provider ids are reserved.",
    { placeholder: "[model_providers.local]" },
  ),
  row(
    "model_providers.<id>.auth",
    "Command-backed provider auth",
    "providers",
    "code",
    "Command-backed bearer token configuration for a custom provider.",
    { placeholder: "[model_providers.local.auth]" },
  ),
  row(
    "model_providers.<id>.auth.cwd",
    "Provider auth working directory",
    "providers",
    "text",
    "Working directory for the provider token command.",
    { placeholder: "~/Code/project" },
  ),
  row(
    "notice.hide_gpt5_1_migration_prompt",
    "Hide GPT-5.1 migration prompt",
    "advanced",
    "toggle",
    "Track acknowledgement of the GPT-5.1 migration prompt.",
    { defaultValue: false },
  ),
  row(
    "notice.hide_gpt-5.1-codex-max_migration_prompt",
    "Hide Codex Max migration prompt",
    "advanced",
    "toggle",
    "Track acknowledgement of the gpt-5.1-codex-max migration prompt.",
    { defaultValue: false },
  ),
  row(
    "notice.hide_world_writable_warning",
    "Hide world-writable warning",
    "advanced",
    "toggle",
    "Track acknowledgement of the Windows world-writable directories warning.",
    { defaultValue: false },
  ),
  row(
    "otel.exporter.<id>.tls.ca-certificate",
    "OTEL CA certificate",
    "telemetry",
    "text",
    "CA certificate path for OTEL exporter TLS.",
    { placeholder: "/path/to/ca.pem" },
  ),
  row(
    "otel.exporter.<id>.tls.client-certificate",
    "OTEL client certificate",
    "telemetry",
    "text",
    "Client certificate path for OTEL exporter TLS.",
    { placeholder: "/path/to/client.pem" },
  ),
  row(
    "otel.exporter.<id>.tls.client-private-key",
    "OTEL client private key",
    "telemetry",
    "text",
    "Client private key path for OTEL exporter TLS.",
    { placeholder: "/path/to/client-key.pem" },
  ),
  row(
    "otel.trace_exporter.<id>.endpoint",
    "OTEL trace endpoint",
    "telemetry",
    "text",
    "Trace exporter endpoint for OTEL traces.",
    { placeholder: "https://otel.example.com/v1/traces" },
  ),
  row(
    "otel.trace_exporter.<id>.protocol",
    "OTEL trace protocol",
    "telemetry",
    "select",
    "Protocol used by the OTLP/HTTP trace exporter.",
    { options: ["binary", "json"], defaultValue: "binary" },
  ),
  row(
    "otel.trace_exporter.<id>.headers",
    "OTEL trace headers",
    "telemetry",
    "code",
    "Static headers included with OTEL trace requests.",
    { placeholder: '{ Authorization = "Bearer ..." }' },
  ),
  row(
    "otel.trace_exporter.<id>.tls.ca-certificate",
    "OTEL trace CA certificate",
    "telemetry",
    "text",
    "CA certificate path for OTEL trace exporter TLS.",
    { placeholder: "/path/to/ca.pem" },
  ),
  row(
    "otel.trace_exporter.<id>.tls.client-certificate",
    "OTEL trace client certificate",
    "telemetry",
    "text",
    "Client certificate path for OTEL trace exporter TLS.",
    { placeholder: "/path/to/client.pem" },
  ),
  row(
    "otel.trace_exporter.<id>.tls.client-private-key",
    "OTEL trace private key",
    "telemetry",
    "text",
    "Client private key path for OTEL trace exporter TLS.",
    { placeholder: "/path/to/client-key.pem" },
  ),
  row(
    "permissions.<name>.workspace_roots.<path>",
    "Profile workspace root",
    "advanced",
    "toggle",
    "Opt a path into a named profile's workspace root set.",
    { defaultValue: true },
  ),
  row(
    "permissions.<name>.filesystem.<path-or-glob>",
    "Profile filesystem path rule",
    "advanced",
    "select",
    "Grant read, write, or deny access for a path or glob.",
    { options: ["read", "write", "deny"], defaultValue: "read" },
  ),
  row(
    "permissions.<name>.network.allow_local_binding",
    "Profile local binding",
    "advanced",
    "toggle",
    "Permit broader local or private-network access through the profile.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "permissions.<name>.network.allow_upstream_proxy",
    "Profile upstream proxy",
    "advanced",
    "toggle",
    "Allow the profile to chain through an upstream proxy.",
    { defaultValue: true },
  ),
  row(
    "permissions.<name>.network.dangerously_allow_all_unix_sockets",
    "Profile all Unix sockets",
    "advanced",
    "toggle",
    "Allow arbitrary Unix socket destinations in the profile.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "permissions.<name>.network.dangerously_allow_non_loopback_proxy",
    "Profile non-loopback proxy",
    "advanced",
    "toggle",
    "Permit non-loopback bind addresses in the profile.",
    { defaultValue: false, risk: "high" },
  ),
  row(
    "permissions.<name>.network.domains.<pattern>",
    "Profile domain rule",
    "advanced",
    "select",
    "Allow or deny an exact host or wildcard domain pattern.",
    { options: ["allow", "deny"], defaultValue: "allow" },
  ),
  row(
    "permissions.<name>.network.enable_socks5",
    "Profile SOCKS5",
    "advanced",
    "toggle",
    "Expose SOCKS5 support in the permissions profile.",
    { defaultValue: true },
  ),
  row(
    "permissions.<name>.network.enable_socks5_udp",
    "Profile SOCKS5 UDP",
    "advanced",
    "toggle",
    "Allow UDP over the profile's SOCKS5 listener.",
    { defaultValue: true },
  ),
  row(
    "permissions.<name>.network.socks_url",
    "Profile SOCKS5 URL",
    "advanced",
    "text",
    "SOCKS5 proxy endpoint used by the profile.",
    { placeholder: "http://127.0.0.1:8081" },
  ),
  row(
    "permissions.<name>.network.unix_sockets",
    "Profile Unix sockets",
    "advanced",
    "code",
    "Unix socket allowlist overrides for a permissions profile.",
    { placeholder: '{ "/var/run/docker.sock" = "deny" }' },
  ),
  row(
    "permissions.<name>.network.unix_sockets.<path>",
    "Profile Unix socket rule",
    "advanced",
    "select",
    "Allow or deny an absolute Unix socket path.",
    { options: ["allow", "deny"], defaultValue: "deny" },
  ),
  row(
    "plugins.<plugin>.mcp_servers.<server>.enabled",
    "Plugin MCP enabled",
    "tools",
    "toggle",
    "Enable or disable a plugin-provided MCP server.",
    { defaultValue: true },
  ),
  row(
    "plugins.<plugin>.mcp_servers.<server>.default_tools_approval_mode",
    "Plugin MCP approval",
    "tools",
    "select",
    "Default approval behavior for plugin-provided MCP tools.",
    { options: ["auto", "prompt", "writes", "approve"], defaultValue: "prompt" },
  ),
  row(
    "plugins.<plugin>.mcp_servers.<server>.enabled_tools",
    "Plugin MCP enabled tools",
    "tools",
    "code",
    "Allow list of tools exposed by a plugin-provided MCP server.",
    { placeholder: '["search"]' },
  ),
  row(
    "plugins.<plugin>.mcp_servers.<server>.disabled_tools",
    "Plugin MCP disabled tools",
    "tools",
    "code",
    "Deny list applied after enabled plugin MCP tools.",
    { placeholder: '["delete"]' },
  ),
  row(
    "plugins.<plugin>.mcp_servers.<server>.tools.<tool>.approval_mode",
    "Plugin MCP per-tool approval",
    "tools",
    "select",
    "Approval behavior override for one plugin-provided MCP tool.",
    { options: ["auto", "prompt", "writes", "approve"] },
  ),
  row(
    "skills.config",
    "Skill overrides",
    "tools",
    "code",
    "Per-skill enablement overrides stored in config.toml.",
    { placeholder: "[[skills.config]]" },
  ),
  row(
    "skills.config.<index>.path",
    "Skill path",
    "tools",
    "text",
    "Path to a skill folder containing SKILL.md.",
    { placeholder: "~/.codex/skills/example" },
  ),
  row(
    "skills.config.<index>.enabled",
    "Skill enabled",
    "tools",
    "toggle",
    "Enable or disable a referenced skill.",
    { defaultValue: true },
  ),
  row(
    "tui",
    "TUI table",
    "tui",
    "code",
    "TUI-specific options such as notifications and keymaps.",
    { placeholder: "[tui]" },
  ),
  row(
    "tui.keymap.<context>.<action> = []",
    "Unbind TUI action",
    "tui",
    "code",
    "Use an empty array to unbind an action in a keymap context.",
    { placeholder: "[]" },
  ),
  row(
    "tui.model_availability_nux.<model>",
    "Model availability NUX",
    "tui",
    "number",
    "Internal startup-tooltip state keyed by model slug.",
    { defaultValue: 0 },
  ),
  row(
    "windows_wsl_setup_acknowledged",
    "Windows WSL setup",
    "advanced",
    "toggle",
    "Track Windows onboarding acknowledgement.",
    { defaultValue: false },
  ),
];

export const sectionCounts = settingOptions.reduce<Record<string, number>>((counts, option) => {
  counts[option.section] = (counts[option.section] ?? 0) + 1;
  return counts;
}, {});
